### ISSUE TITLE
Tick vs FPS

### ISSUE THREAD

**Issue by leparrain777** [Kh4n/TrackmaniaAKAlternative#1]
Just a heads up, I am pretty sure Trackmania uses a fixed 100 tick/s for all of its inputs, meaning that using 120 instead of 100 for your fps value will give less precise and somewhat inconsistent results. Cool project though and thanks for sharing, it should provide enough scaffolding to implement my own geometric decay steer idea.

**Comment by Kh4n** [comment]
i don't think it would be inconsistent because even if i reduce the tick rate it would need to sync with the Trackmania tick rate, so having a higher tick rate would probably be better. also controllers have a very high tick rate so it probably good to keep it higher than TM tick rate. Lmk if you run into an issue related to the tick rate! Also interested to see what you create with this :)

**Comment by Kh4n** [comment]
Just looked it up: XBox controllers have a polling rate of 125hz, playstation 1000hz. So i think 120 is good

**Comment by leparrain777** [comment]
There is no sync between trackmania inputs and the Xinput controller, so if you were feeding in steering values for example of {0 at 0.00s, 4 at .0083s, 8 at .0166s, 12 at .025s,16 at .0333s, 20 at .0416s, 24 at .0500s, 28 at .0583s} trackmania would pick up {0 at 0, 4 at .01s, 8 at .02s, 12 at .03s, would pick up 16 at .04s, **_and would skip 20 straight to 24 at .05s_**}. So it will be skipping intended inputs, or doubling intended inputs depending on when you start the script unless it is at the same Hz for input. It shouldn't be a major problem, but I don't see why you would use a value that isn't 100 as you will just get more desynch and use extra compute for it. Also you can check your forks, mine is on github under the branch geometricdecay. Works pretty well IMHO, I am definitely getting faster times consistently on some segments.

**Comment by Kh4n** [comment]
well a major reason is for smoother control. current i use 240hz (doubled it from 120hz for this exact reason) so that steering is 1% / 240th of a second and decays to .375%. if i use 100hz those values have to be more than double, which makes it very hard to control
